### ISSUE TITLE
error in build.rs when build proto 3 file

### ISSUE THREAD

**Issue by blueeyezhy** [Xu-Mj/synapse#2]
``` called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: hub.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.\n" }```

Should add a statement in build.rs:
```tonic_build::configure()
        .protoc_arg("--experimental_allow_proto3_optional")
        .out_dir("src/pb")
```

**Comment by Xu-Mj** [comment]
#3
